version: '3.8'

services:
  database:
    container_name: database
    image: postgres:14.1
    environment:
      POSTGRES_DATABASE: smn
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: smn
    expose:
      - "5434"
    ports:
      - "5434:5434"
    volumes:
      - dbdata:/var/lib/postgresql/database
    command: -p 5434

  user_service:
    container_name: user_service
    build: 
      context: ./user_service
      # args:
      #   MAKE_TARGET: migrate_up
    depends_on:
      - "kafka"
      - "database"
    ports:
      - "8000:8000"

  post_service:
    container_name: post_service
    build: 
      context: ./post_service
      # args:
      #   MAKE_TARGET: migrate_up
    depends_on:
      - "kafka"
      - "database"
    ports:
      - "8010:8010"

  comment_service:
    container_name: comment_service
    build: 
      context: ./comment_service
      # args:
      #   MAKE_TARGET: migrate_up
    depends_on:
      - "database"
    ports:
      - "8020:8020"

  api:
    container_name: api_gateway
    build: 
      context: ./api_gateway
      # args:
      #   MAKE_TARGET: migrate_up
    depends_on:
      - "redisdb"
      - "user_service"
      - "post_service"
      - "comment_service"
    ports:
      - "5050:5050"

  redisdb:
    container_name: redisdb
    image: redis 
    ports:
      - "6380:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  dbdata:
